project:
  name: quickstart-salesforce-health-cloud-virtual-care
  owner: quickstart-eng@amazon.com
  template: templates/salesforce-health-cloud-virtual-care.template.yaml
  parameters:
    Username: override
    Password: override
    OAuthClientID: override
    OAuthClientSecret: override
    InstanceName: override
    PlatformEndpointVersion: override
    IsCustomPlatformEventEndpoint: override
    RateLimit: 5
    AlarmEmail: override
    IamUserName: $[taskcat_genpass_8A]
    IamPassword: $[taskcat_genpass_128S]
    IamGroupName: $[taskcat_genpass_8A]
  regions:
    - af-south-1
    - ap-east-1
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-north-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - me-south-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - us-gov-west-1
  # regions-not-yet-supported:
  # # One or more required services aren't available yet in these regions
  #   - ap-northeast-3
  #   - ap-southeast-3
tests:
  default:
    regions:
      - us-east-1
