AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template to create resources required to send Chime events to Salesforce. (qs-1ssngicuj)
Metadata:
  LintSpellExclude:
    - Salesforce
    - OAuth
  SentenceCaseExclude:
    - Developer
    - Edition
    - Production
    - Trial
  LICENSE: Apache License, Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Salesforce credentials
        Parameters:
          - Username
          - Password
      - Label:
          default: Salesforce OAuth configuration
        Parameters:
          - OAuthClientID
          - OAuthClientSecret
      - Label:
          default: Salesforce platform event endpoint configuration
        Parameters:
          - InstanceName
          - SandboxName
          - IsEnhancedSandbox
          - PlatformEndpointVersion
          - RateLimit
          - IsCustomPlatformEventEndpoint
      - Label:
          default: Event processing retry configuration
        Parameters:
          - MaximumRetryAttempts
          - MaximumEventAgeInSeconds
      - Label:
          default: Dead letter queue configuration
        Parameters:
          - DeadLetterQueueName
          - MessageRetentionPeriod
          - AlarmEmail
          - QueueDepthAlarmPeriod
          - QueueDepthAlarmEvaluationPeriods
          - QueueDepthAlarmThreshold
    ParameterLabels:
      Username:
        default: Username
      Password:
        default: Password
      OAuthClientID:
        default: OAuth client ID
      OAuthClientSecret:
        default: OAuth client secret
      InstanceName:
        default: Instance name
      SandboxName:
        default: Sandbox name
      IsEnhancedSandbox:
        default: Enhanced sandbox domain
      PlatformEndpointVersion:
        default: Version
      IsCustomPlatformEventEndpoint:
        default: Is this a custom platform event endpoint?
      RateLimit:
        default: Rate limit
      MaximumRetryAttempts:
        default: Max retries
      MaximumEventAgeInSeconds:
        default: Max age
      DeadLetterQueueName:
        default: Name
      MessageRetentionPeriod:
        default: Retention period
      AlarmEmail:
        default: Email address
      QueueDepthAlarmPeriod:
        default: Alarm period
      QueueDepthAlarmEvaluationPeriods:
        default: Alarm evaluation periods
      QueueDepthAlarmThreshold:
        default: Alarm threshold
Parameters:
  Username:
    Type: String
    Description: Salesforce username.
  Password:
    Type: String
    Description: Salesforce password.
    NoEcho: True
  OAuthClientID:
    Type: String
    Description: Salesforce provided OAuth client ID.
    NoEcho: True
  OAuthClientSecret:
    Type: String
    Description: Salesforce provided OAuth client secret.
    NoEcho: True
  InstanceName:
    Type: String
    Description: >-
      Salesforce instance domain. Example:
      'https://<InstanceName>.my.salesforce.com/'.
  SandboxName:
    Type: String
    Description: >-
      (Optional) If using a Salesforce sandbox, enter the sandbox name;
      otherwise, leave blank.
    Default: ''
  IsEnhancedSandbox:
    Type: String
    Description: >-
      Choose yes if using a Salesforce sandbox with an enhanced domain.
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  PlatformEndpointVersion:
    Type: String
    Description: Salesforce platform event endpoint version to use.
    Default: v55.0
  IsCustomPlatformEventEndpoint:
    Type: String
    Description: >-
      Choose yes if using a Salesforce custom platform event endpoint for
      testing purposes.
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  RateLimit:
    Type: Number
    Description: >-
      Rate limit for Amazon EventBridge to the Salesforce platform event
      endpoint. The default soft limit is 25 for Production organizations &
      Sandboxes, and the default soft limit is 5 for Developer Edition & Trial
      organizations. Reference:
      'https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_api.htm'.
    MinValue: 1
    Default: 25
  MaximumRetryAttempts:
    Type: Number
    Description: >-
      The maximum number of retry attempts to make before the request fails.
      Retry attempts continue until either the maximum number of attempts is
      made or until the duration of the MaximumEventAgeInSeconds is met.
    MinValue: 0
    MaxValue: 185
    Default: 4
  MaximumEventAgeInSeconds:
    Type: Number
    Description: >-
      The maximum amount of time, in seconds, to continue to make retry
      attempts.
    MinValue: 60 # 1 minute
    MaxValue: 86400 # 1 day
    Default: 400 # 6.7 minutes
  DeadLetterQueueName:
    Type: String
    Description: >-
      Name of the Amazon SQS dead-letter queue for temporarily storing events
      that failed to deliver.
    AllowedPattern: '[a-zA-Z0-9-_]+'
    ConstraintDescription: >-
      Can only include alphanumeric characters, hyphens, or underscores.
      1 to 80 in length.
    MinLength: 1
    MaxLength: 80
    Default: SalesforceDLQ
  MessageRetentionPeriod:
    Type: Number
    Description: >-
      The number of seconds that messages are retained in the dead-letter
      queue.
    MinValue: 60 # 1 minute
    MaxValue: 1209600 # 14 days
    Default: 345600 # 4 days
  AlarmEmail:
    Type: String
    Description: Email address to notify of operational issues.
    MinLength: 1
  QueueDepthAlarmPeriod:
    Type: Number
    Description: >-
      The period, in seconds, over which the statistic is applied. Valid values
      are 10, 30, 60, and any multiple of 60.
    MinValue: 10
    Default: 300 # 5 minutes
  QueueDepthAlarmEvaluationPeriods:
    Type: Number
    Description: >-
      The number of periods over which the number messages in the dead-letter
      queue is compared to the specified threshold.
    MinValue: 1
    Default: 1
  QueueDepthAlarmThreshold:
    Type: Number
    Description: >-
      The threshold number of messages in the dead-letter queue to trigger an
      alarm. If set to 0, the Amazon CloudWatch alarm and Amazon SNS topic will
      not be deployed- disabling the dead-letter queue monitoring and email
      alerts.
    MinValue: 0
    Default: 10
Conditions:
  IsEnhancedSandbox: !And [!Not [!Equals [!Ref SandboxName, '']], !Equals [!Ref IsEnhancedSandbox, 'true']]
  IsCustomPlatformEventEndpoint: !Equals [!Ref IsCustomPlatformEventEndpoint, 'true']
  IsSandbox: !Not [!Equals [!Ref SandboxName, '']]
  CreateAlarm: !Not [!Equals [!Ref QueueDepthAlarmThreshold, 0]]
Resources:
  SalesforceApiDestinationRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Amazon EventBus API Destination Role
      RoleName: Salesforce_EventBridge_Invoke_Api_Destination
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      Policies:
        - PolicyName: SalesforceApiDestinationPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - events:InvokeApiDestination
                Resource: !GetAtt SalesforceApiDestination.Arn
  SalesforceConnectionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: SalesforceOAuthSecret
      Description: OAuth connection credential secret.
      SecretString: !Sub '{"ClientID": "${OAuthClientID}", "ClientSecret": "${OAuthClientSecret}", "Username": "${Username}", "Password": "${Password}"}'
  SalesforceOAuthConnection:
    Type: AWS::Events::Connection
    Properties:
      Name: SalesforceOAuthConnection
      AuthorizationType: OAUTH_CLIENT_CREDENTIALS
      AuthParameters:
        OAuthParameters:
          AuthorizationEndpoint: !Sub
            - https://${InstanceName}${SandboxSuffix}${EnhancedSandboxDomain}.my.salesforce.com/services/oauth2/token
            - SandboxSuffix: !If [IsSandbox, !Sub '--${SandboxName}', '']
              EnhancedSandboxDomain: !If [IsEnhancedSandbox, '.sandbox', '']
          ClientParameters:
            ClientID: '{{resolve:secretsmanager:SalesforceOAuthSecret:SecretString:ClientID}}'
            ClientSecret: '{{resolve:secretsmanager:SalesforceOAuthSecret:SecretString:ClientSecret}}'
          HttpMethod: POST
          OAuthHttpParameters:
            BodyParameters:
              - IsValueSecret: false
                Key: grant_type
                Value: password
              - IsValueSecret: false
                Key: username
                Value: '{{resolve:secretsmanager:SalesforceOAuthSecret:SecretString:Username}}'
              - IsValueSecret: true
                Key: password
                Value: '{{resolve:secretsmanager:SalesforceOAuthSecret:SecretString:Password}}'
    DependsOn: SalesforceConnectionSecret
  SalesforceApiDestination:
    Type: AWS::Events::ApiDestination
    Properties:
      ConnectionArn: !GetAtt SalesforceOAuthConnection.Arn
      Description: >-
        API destination to send events to Salesforce platform event endpoint.
      HttpMethod: POST
      InvocationEndpoint: !Sub
        - https://${InstanceName}.my.salesforce.com/services/data/${PlatformEndpointVersion}/sobjects/ServiceProviderEvent${Suffix}
        - Suffix: !If [IsCustomPlatformEventEndpoint, __e, '']
      InvocationRateLimitPerSecond: !Ref RateLimit
  SalesforceEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Rule to use API Destination with Input Transformer
      State: ENABLED
      EventPattern:
        source:
          - aws.chime
      RoleArn: !GetAtt SalesforceApiDestinationRole.Arn
      Targets:
        - Id: Salesforce-destination
          Arn: !GetAtt SalesforceApiDestination.Arn
          RetryPolicy:
            MaximumRetryAttempts: !Ref MaximumRetryAttempts
            MaximumEventAgeInSeconds: !Ref MaximumEventAgeInSeconds
          DeadLetterConfig:
            Arn: !GetAtt DeadLetterQueue.Arn
          RoleArn: !GetAtt SalesforceApiDestinationRole.Arn
          InputTransformer:
            InputPathsMap:
              source: $.source
              account: $.account
              id: $.id
              region: $.region
              detail-type: $.detail-type
              time: $.time
              eventType: $.detail.eventType
              timestamp: $.detail.timestamp
              meetingId: $.detail.meetingId
              externalMeetingId: $.detail.externalMeetingId
              attendeeId: $.detail.attendeeId
              externalUserId: $.detail.externalUserId
              mediaRegion: $.detail.mediaRegion
              networkType: $.detail.networkType
            InputTemplate: '{"ServiceName" : "<source>","Json" : "{\r\n\"source\": \"<source>\",\r\n\"account\": \"<account>\",\r\n\"id\": \"<id>\",\r\n\"region\": \"<region>\",\r\n\"detail-type\": \"<detail-type>\",\r\n\"time\": \"<time>\",\r\n\"detail\": {\r\n\"eventType\": \"<eventType>\",\r\n\"timestamp\": \"<timestamp>\",\r\n\"meetingId\": \"<meetingId>\",\r\n\"externalMeetingId\": \"<externalMeetingId>\",\r\n\"attendeeId\": \"<attendeeId>\",\r\n\"externalUserId\": \"<externalUserId>\",\r\n\"mediaRegion\": \"<mediaRegion>\",\r\n\"networkType\":\"<networkType>\"\r\n}\r\n}"}'
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref DeadLetterQueueName
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
  AlarmTopic:
    Type: AWS::SNS::Topic
    Condition: CreateAlarm
    Properties:
      DisplayName: !Sub ${DeadLetterQueueName}-topic
      Subscription:
        - Endpoint: !Ref AlarmEmail
          Protocol: email
  QueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: CreateAlarm
    Properties:
      AlarmDescription: >-
        Alarm if the Salesforce dead-letter queue depth exceeds the specified
        number of messages.
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DeadLetterQueue.QueueName
      Statistic: Sum
      Period: !Ref QueueDepthAlarmPeriod
      EvaluationPeriods: !Ref QueueDepthAlarmEvaluationPeriods
      Threshold: !Ref QueueDepthAlarmThreshold
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmTopic
      TreatMissingData: ignore
