AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template to create resources required to send Chime events to Salesforce. (qs-1ssngicuj)
Metadata:
  LintSpellExclude:
    - Salesforce
    - OAuth
  SentenceCaseExclude:
    - Developer
    - Edition
    - If
    - Production
    - Trial
  LICENSE: Apache License, Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Salesforce credentials configuration
        Parameters:
          - SalesforceUsername
          - SalesforcePassword
      - Label:
          default: Salesforce OAuth configuration
        Parameters:
          - SalesforceAuthorizationEndpoint
          - SalesforceOAuthClientID
          - SalesforceOAuthClientSecret
      - Label:
          default: Salesforce platform event endpoint configuration
        Parameters:
          - SalesforcePlatformEventEndpoint
          - SalesforcePlatformEventEndpointRateLimit
      - Label:
          default: Service account
        Parameters:
          - IamUserName
          - IamPassword
          - IamGroupName
      - Label:
          default: Event processing retry configuration
        Parameters:
          - MaximumRetryAttempts
          - MaximumEventAgeInSeconds
      - Label:
          default: Dead letter queue configuration
        Parameters:
          - DlqName
          - DlqCmkAlias
          - DlqKmsDataKeyReusePeriod
          - DlqMessageRetentionPeriod
          - DlqQueueDepthAlarmPeriod
          - DlqQueueDepthAlarmEvaluationPeriods
          - DlqQueueDepthAlarmThreshold
          - DlqAlarmEmail
    ParameterLabels:
      SalesforceUsername:
        default: Username
      SalesforcePassword:
        default: Password
      SalesforceOAuthClientID:
        default: Client ID
      SalesforceOAuthClientSecret:
        default: Client secret
      SalesforceAuthorizationEndpoint:
        default: Endpoint URL
      SalesforcePlatformEventEndpoint:
        default: Endpoint URL
      SalesforcePlatformEventEndpointRateLimit:
        default: Rate limit
      MaximumRetryAttempts:
        default: Max retries
      MaximumEventAgeInSeconds:
        default: Max age
      DlqName:
        default: Name
      DlqCmkAlias:
        default: CMK alias
      DlqKmsDataKeyReusePeriod:
        default: Data key reuse period
      DlqMessageRetentionPeriod:
        default: Retention period
      DlqAlarmEmail:
        default: Email address
      DlqQueueDepthAlarmPeriod:
        default: Alarm period
      DlqQueueDepthAlarmEvaluationPeriods:
        default: Alarm evaluation periods
      DlqQueueDepthAlarmThreshold:
        default: Alarm threshold
      IamUserName:
        default: Username
      IamPassword:
        default: Password
      IamGroupName:
        default: Group name
Parameters:
  SalesforceUsername:
    Type: String
    Description: >-
      Salesforce username that will be stored in AWS Secrets Manager and used
      by Amazon EventBridge for authentication when sending events.
    MinLength: 1
  SalesforcePassword:
    Type: String
    Description: >-
      Salesforce password that will be stored in AWS Secrets Manager and used
      by Amazon EventBridge for authentication when sending events.
    NoEcho: True
    MinLength: 8
  SalesforceOAuthClientID:
    Type: String
    Description: >-
      Salesforce provided OAuth client ID that will be stored in
      AWS Secrets Manager and used by Amazon EventBridge for authentication
      when sending events.
    NoEcho: True
    MinLength: 1
  SalesforceOAuthClientSecret:
    Type: String
    Description: >-
      Salesforce provided OAuth client secret that will be stored in
      AWS Secrets Manager and used by Amazon EventBridge for authentication
      when sending events.
    NoEcho: True
    MinLength: 1
  SalesforceAuthorizationEndpoint:
    Type: String
    Description: >-
      Salesforce OAuth authorization endpoint URL. Example:
      'https://<InstanceName>.my.salesforce.com/services/oauth2/token'.
    MinLength: 31
    AllowedPattern: ^https:\/\/[a-z]([a-z0-9-\.]*[a-z])*/services/oauth2/token$
    ConstraintDescription: >-
      Must be a valid Salesforce authorization endpoint URL.
  SalesforcePlatformEventEndpoint:
    Type: String
    Description: >-
      Salesforce platform event endpoint URL. Example:
      'https://<InstanceName>.my.salesforce.com/services/data/v55.0/sobjects/ServiceProviderEvent'.
    MinLength: 58
    AllowedPattern: ^https:\/\/[a-z]([a-z0-9-\.]*[a-z])*/services/data/v\d+\.\d/sobjects/ServiceProviderEvent(__e)?$
    ConstraintDescription: >-
      Must be a valid Salesforce platform event endpoint URL.
  SalesforcePlatformEventEndpointRateLimit:
    Type: Number
    Description: >-
      Rate limit for Amazon EventBridge to the Salesforce platform event
      endpoint. The default soft limit is 25 for Production organizations &
      Sandboxes, and the default soft limit is 5 for Developer Edition & Trial
      organizations. Reference:
      'https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_api.htm'.
    MinValue: 1
    Default: 25
  MaximumRetryAttempts:
    Type: Number
    Description: >-
      The maximum number of retry attempts to make before the request fails.
      Retry attempts continue until either the maximum number of attempts is
      made or until the duration of the MaximumEventAgeInSeconds is met.
    MinValue: 0
    MaxValue: 185
    Default: 4
  MaximumEventAgeInSeconds:
    Type: Number
    Description: >-
      The maximum amount of time, in seconds, to continue to make retry
      attempts.
    MinValue: 60 # 1 minute
    MaxValue: 86400 # 1 day
    Default: 400 # 6.7 minutes
  DlqName:
    Type: String
    Description: >-
      Name of the Amazon SQS dead-letter queue for temporarily storing events
      that failed to deliver.
    MinLength: 1
    MaxLength: 80
    AllowedPattern: ^[a-zA-Z0-9-_]+$
    ConstraintDescription: >-
      Can only include alphanumeric characters, hyphens, or underscores.
    Default: SalesforceDLQ
  DlqCmkAlias:
    Type: String
    Description: >-
      The alias of a symmetric AWS KMS customer managed key (CMK) to use for
      server-side encryption of any Amazon Chime messages stored in the
      Amazon SQS dead-letter queue. The default is to use the AWS managed CMK
      for Amazon SQS (SSE-SQS). Alternatively, enter the alias of your custom
      CMK.
    MinLength: 7
    MaxLength: 262
    AllowedPattern: ^alias/[a-zA-Z0-9/_-]+$
    ConstraintDescription: >-
      The CMK alias must start with 'alias/'. It can contain only alphanumeric
      characters, forward slashes (/), underscores (_), and dashes (-).
    Default: alias/aws/sqs
  DlqKmsDataKeyReusePeriod:
    Type: Number
    Description: >-
      The length of time in seconds for which Amazon SQS can reuse a data key
      to encrypt or decrypt messages before calling AWS KMS again. Note: A
      shorter time period provides better security, but results in more calls
      to AWS KMS, which might incur charges after Free Tier.
    MinValue: 60 # 1 minute
    MaxValue: 86400 # 1 day
    Default: 300 # 5 minutes
  DlqMessageRetentionPeriod:
    Type: Number
    Description: >-
      The number of seconds that messages are retained in the dead-letter
      queue. The default is 4 days.
    MinValue: 60 # 1 minute
    MaxValue: 1209600 # 14 days
    Default: 345600 # 4 days
  DlqAlarmEmail:
    Type: String
    Description: Email address to notify of operational issues.
    MinLength: 1
  DlqQueueDepthAlarmPeriod:
    Type: Number
    Description: >-
      The period, in seconds, over which the statistic is applied. Valid values
      are 10, 30, 60, and any multiple of 60.
    MinValue: 10
    Default: 300 # 5 minutes
  DlqQueueDepthAlarmEvaluationPeriods:
    Type: Number
    Description: >-
      The number of periods over which the number messages in the dead-letter
      queue is compared to the specified threshold.
    MinValue: 1
    Default: 1
  DlqQueueDepthAlarmThreshold:
    Type: Number
    Description: >-
      The threshold number of messages in the dead-letter queue to trigger an
      alarm. If set to 0, the Amazon CloudWatch alarm and Amazon SNS topic will
      not be deployed- disabling the dead-letter queue monitoring and email
      alerts.
    MinValue: 0
    Default: 10
  IamUserName:
    Type: String
    Description: >-
      Username for the AWS IAM user account that will be used as the Salesforce
      named credential service account.
    MinLength: 1
    MaxLength: 64
    AllowedPattern: ^[\w+=,.@-]+$
    ConstraintDescription: >-
      Use alphanumeric or any of the following symbols: _+=,.@-
    Default: salesforce
  IamPassword:
    Type: String
    Description: >-
      Password for the AWS IAM user account that will be used as the Salesforce
      named credential service account.
    NoEcho: True
    MinLength: 8
    MaxLength: 128
  IamGroupName:
    Type: String
    Description: >-
      Name for the AWS IAM group that grants the AWS IAM user account the
      necessary permissions via the associated AWS managed AmazonChimeSDK
      IAM policy.
    MinLength: 1
    MaxLength: 128
    AllowedPattern: ^[\w+=,.@-]+$
    ConstraintDescription: >-
      Use alphanumeric or any of the following symbols: _+=,.@-
    Default: salesforce
Conditions:
  CreateAlarm: !Not [!Equals [!Ref DlqQueueDepthAlarmThreshold, 0]]
Resources:
  IamGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref IamGroupName
      Path: /salesforce/
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonChimeSDK
  IamUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref IamUserName
      LoginProfile:
        Password: !Ref IamPassword
        PasswordResetRequired: False
      Path: /salesforce/
      Groups:
        - !Ref IamGroup
  ChimeTranscriptionSlr:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: transcription.chime.amazonaws.com
      Description: >-
        Amazon Chime service linked role with pre-defined permissions to allow
        the service to call other AWS services on your behalf for performing
        transcription.
  SalesforceApiDestinationRole:
    Type: AWS::IAM::Role
    Properties:
      Description: >-
        Amazon EventBridge destination role for invoking the Salesforce service
        provider event API endpoint.
      RoleName: Salesforce_EventBridge_Invoke_Api_Destination
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      Policies:
        - PolicyName: SalesforceApiDestinationPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - events:InvokeApiDestination
                Resource: !GetAtt SalesforceApiDestination.Arn
  SalesforceConnectionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: SalesforceOAuthSecret
      Description: OAuth connection credential secret.
      SecretString: !Sub >-
        {
          "ClientID": "${SalesforceOAuthClientID}",
          "ClientSecret": "${SalesforceOAuthClientSecret}",
          "Username": "${SalesforceUsername}",
          "Password": "${SalesforcePassword}"
        }
  SalesforceOAuthConnection:
    Type: AWS::Events::Connection
    Properties:
      Name: SalesforceOAuthConnection
      AuthorizationType: OAUTH_CLIENT_CREDENTIALS
      AuthParameters:
        OAuthParameters:
          AuthorizationEndpoint: !Ref SalesforceAuthorizationEndpoint
          ClientParameters:
            ClientID: '{{resolve:secretsmanager:SalesforceOAuthSecret:SecretString:ClientID}}'
            ClientSecret: '{{resolve:secretsmanager:SalesforceOAuthSecret:SecretString:ClientSecret}}'
          HttpMethod: POST
          OAuthHttpParameters:
            BodyParameters:
              - IsValueSecret: false
                Key: grant_type
                Value: password
              - IsValueSecret: false
                Key: username
                Value: '{{resolve:secretsmanager:SalesforceOAuthSecret:SecretString:Username}}'
              - IsValueSecret: true
                Key: password
                Value: '{{resolve:secretsmanager:SalesforceOAuthSecret:SecretString:Password}}'
    DependsOn: SalesforceConnectionSecret
  SalesforceApiDestination:
    Type: AWS::Events::ApiDestination
    Properties:
      ConnectionArn: !GetAtt SalesforceOAuthConnection.Arn
      Description: >-
        API destination to send events to Salesforce platform event endpoint.
      HttpMethod: POST
      InvocationEndpoint: !Ref SalesforcePlatformEventEndpoint
      InvocationRateLimitPerSecond: !Ref SalesforcePlatformEventEndpointRateLimit
  SalesforceEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Rule to use API Destination with Input Transformer
      State: ENABLED
      EventPattern:
        source:
          - aws.chime
      RoleArn: !GetAtt SalesforceApiDestinationRole.Arn
      Targets:
        - Id: Salesforce-destination
          Arn: !GetAtt SalesforceApiDestination.Arn
          RetryPolicy:
            MaximumRetryAttempts: !Ref MaximumRetryAttempts
            MaximumEventAgeInSeconds: !Ref MaximumEventAgeInSeconds
          DeadLetterConfig:
            Arn: !GetAtt DeadLetterQueue.Arn
          RoleArn: !GetAtt SalesforceApiDestinationRole.Arn
          InputTransformer:
            InputPathsMap:
              source: $.source
              account: $.account
              id: $.id
              region: $.region
              detail-type: $.detail-type
              time: $.time
              eventType: $.detail.eventType
              timestamp: $.detail.timestamp
              meetingId: $.detail.meetingId
              externalMeetingId: $.detail.externalMeetingId
              attendeeId: $.detail.attendeeId
              externalUserId: $.detail.externalUserId
              mediaRegion: $.detail.mediaRegion
              networkType: $.detail.networkType
            InputTemplate: '{
                "ServiceName": "<source>",
                "Json": "{
                  \"source\": \"<source>\",
                  \"account\": \"<account>\",
                  \"id\": \"<id>\",
                  \"region\": \"<region>\",
                  \"detail-type\": \"<detail-type>\",
                  \"time\": \"<time>\",
                  \"detail\": {
                    \"eventType\": \"<eventType>\",
                    \"timestamp\": \"<timestamp>\",
                    \"meetingId\": \"<meetingId>\",
                    \"externalMeetingId\": \"<externalMeetingId>\",
                    \"attendeeId\": \"<attendeeId>\",
                    \"externalUserId\": \"<externalUserId>\",
                    \"mediaRegion\": \"<mediaRegion>\",
                    \"networkType\": \"<networkType>\"
                  }
                }"
              }'
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref DlqName
      MessageRetentionPeriod: !Ref DlqMessageRetentionPeriod
      KmsMasterKeyId: !Ref DlqCmkAlias
      KmsDataKeyReusePeriodSeconds: !Ref DlqKmsDataKeyReusePeriod
  AlarmTopic:
    Type: AWS::SNS::Topic
    Condition: CreateAlarm
    Properties:
      DisplayName: !Sub ${DlqName}-topic
      Subscription:
        - Endpoint: !Ref DlqAlarmEmail
          Protocol: email
  QueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: CreateAlarm
    Properties:
      AlarmDescription: >-
        Alarm if the Salesforce dead-letter queue depth exceeds the specified
        number of messages.
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DeadLetterQueue.QueueName
      Statistic: Sum
      Period: !Ref DlqQueueDepthAlarmPeriod
      EvaluationPeriods: !Ref DlqQueueDepthAlarmEvaluationPeriods
      Threshold: !Ref DlqQueueDepthAlarmThreshold
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmTopic
      TreatMissingData: ignore
Outputs:
  Postdeployment:
    Description: See the deployment guide for post-deployment steps.
    Value: https://aws-quickstart.github.io/quickstart-salesforce-health-cloud-virtual-care/#_postdeployment_steps
